### ISSUE TITLE
Fix http issue

### ISSUE THREAD

**Issue by kris10anebratlie** [bcc-code/buk-universal-games#77] opened 2024-05-30 22:28 UTC

**Comment by Zikoat** [comment] 2024-06-04 20:20
If the http type isn't specified on iphone safari, then it says couldn't load page.
If specifically http is used on mac safari, then it says couldn't load the page.
I currently don't have an iphone or mac to test this with, but i will find one.

**Comment by Zikoat** [comment] 2024-06-04 20:20
Kristiane can unsubscribe to notifications here.

**Comment by Zikoat** [comment] 2024-06-06 14:25
So i haven't been able to figure out yet what the cause of this is, or how i can fix it.
We can workaround this by just adding https:// to the beginning of the urls.

**Comment by Zikoat** [comment] 2024-06-23 17:25
Closing. Will use workaround.

**Closed** 2024-06-23 17:24 UTC
